<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.wly.job</groupId>
        <artifactId>samples</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <groupId>com.wly.job.samples</groupId>
    <artifactId>register-center-registry-sample</artifactId>
    <name>register-center-registry-sample</name>

    <dependencies>
        <dependency>
            <groupId>com.wly.config</groupId>
            <artifactId>core</artifactId>
        </dependency>
    </dependencies>
</project>
